### ISSUE TITLE
Couldn't find any filter plugin named 'date'

### ISSUE THREAD

**Issue by jnsreddy9999** [logstash-plugins/logstash-filter-date#101]
I'm trying to setup the logstash. I used the "date" filter in my config file. When I try to run the logstash, got the below error. Can someone help me to resolve this?

Error:

[2017-05-21T23:13:05,734][ERROR][logstash.plugins.registry] Problems loading a p
lugin with {:type=>"filter", :name=>"date", :path=>"logstash/filters/date", :err
or_message=>"\n\n\tyou might need to reinstall the gem which depends on the miss
ing jar or in case there is Jars.lock then resolve the jars with `lock_jars` com
mand\n\nno such file to load -- org/logstash/filters/logstash-filter-date/3.1.0/
logstash-filter-date-3.1.0 (LoadError)", :error_class=>RuntimeError, :error_back
trace=>["C:/Nagasayana/Softwares/Kibana/logstash-5.2.2/vendor/bundle/jruby/1.9/g
ems/jar-dependencies-0.3.10/lib/jar_dependencies.rb:348:in `do_require'", "C:/Na
gasayana/Softwares/Kibana/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/jar-depend
encies-0.3.10/lib/jar_dependencies.rb:255:in `require_jar'", "C:/Nagasayana/Soft
wares/Kibana/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.10
/lib/jar_dependencies.rb:0:in `require_jar_with_block'", "C:/Nagasayana/Software
s/Kibana/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.10/lib
/jar_dependencies.rb:254:in `require_jar'", "C:/Nagasayana/Softwares/Kibana/logs
tash-5.2.2/lib/bootstrap/patches/jar_dependencies.rb:6:in `require_jar'", "C:/Na
gasayana/Softwares/Kibana/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-f
ilter-date-3.1.3/lib/logstash-filter-date_jars.rb:4:in `(root)'", "org/jruby/Rub
yKernel.java:1040:in `require'", "C:/Nagasayana/Softwares/Kibana/logstash-5.2.2/
vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "C

- Version: logstash-5.2.2
- Operating System: Windows7 64bit
- Config File (if you have sensitive info, please remove it):
- Sample Data:

input {
  file {
    path => "access_log"
    start_position => "beginning"
  }
}

filter {
  if [path] =~ "access" {
    mutate { replace => { "type" => "xxxxxxxxx" } }
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
  }
  stdout { codec => rubydebug }
}
- Steps to Reproduce:

**Comment by jnsreddy9999** [comment]
Hi All,

Can someone please help me out?

**Comment by jsvd** [comment]
was this logstash installation upgraded from a previous version of logstash? can you upgrade the logstash-filter-date plugin to 3.1.5 and see if the problem persists?
