### ISSUE TITLE
Unit test broken for JDK7

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-filter-date#39]
See: http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20Filters/job/logstash-plugin-filter-date-unit/jdk=JDK7,nodes=metal-pool/14/console

```
Using bundler 1.10.6
Bundle complete! 2 Gemfile dependencies, 38 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
..........F...F....F...................................

Failures:

  1) LogStash::Filters::Date fill next year if january events arrive in december "Jan 01 01:00:00" when processed
     Failure/Error: insist { subject["@timestamp"].year } == 2014
       (<Time (class)>).now(no args)
           expected: 2 times with any arguments
           received: 3 times
     # ./lib/logstash/filters/date.rb:277:in `filter'
     # ./lib/logstash/filters/date.rb:243:in `filter'
     # ./lib/logstash/filters/date.rb:236:in `filter'
     # (eval):33:in `filter_func'
     # ./spec/filters/date_spec.rb:434:in `(root)'
     # ./spec/filters/date_spec.rb:434:in `(root)'

  2) LogStash::Filters::Date fill last year if december events arrive in january "Dec 31 23:59:00" when processed
     Failure/Error: insist { subject["@timestamp"].year } == 2013
       (<Time (class)>).now(no args)
           expected: 2 times with any arguments
           received: 3 times
     # ./lib/logstash/filters/date.rb:277:in `filter'
     # ./lib/logstash/filters/date.rb:243:in `filter'
     # ./lib/logstash/filters/date.rb:236:in `filter'
     # (eval):33:in `filter_func'
     # ./spec/filters/date_spec.rb:416:in `(root)'
     # ./spec/filters/date_spec.rb:416:in `(root)'

  3) LogStash::Filters::Date parsing with java SimpleDateFormat syntax "{"mydate":"Nov 24 01:29:01 -0800"}" when processed
     Failure/Error: insist { subject["@timestamp"].time } == Time.iso8601(output).utc
     Insist::Failure:
       Expected 2015-11-24 09:29:01 UTC, but got 2015-11-17 13:36:33 UTC
     # ./spec/filters/date_spec.rb:99:in `(root)'

Finished in 1.25 seconds (files took 1.42 seconds to load)
55 examples, 3 failures
```

**Comment by wiibaa** [comment]
@suyograo can you close please
