### ISSUE TITLE
Tests failing under JDK7

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-date#49]
http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20Filters/job/logstash-plugin-filter-date-unit/jdk=JDK7,nodes=metal-pool/11/console

**Comment by jordansissel** [comment]
```
Failures:

  1) LogStash::Filters::Date fill next year if january events arrive in december "Jan 01 01:00:00" when processed
     Failure/Error: insist { subject["@timestamp"].year } == 2014
       (<Time (class)>).now(no args)
           expected: 2 times with any arguments
           received: 3 times
     # ./lib/logstash/filters/date.rb:275:in `filter'
     # ./lib/logstash/filters/date.rb:241:in `filter'
     # ./lib/logstash/filters/date.rb:234:in `filter'
     # (eval):33:in `filter_func'
     # ./spec/filters/date_spec.rb:431:in `(root)'
     # ./spec/filters/date_spec.rb:431:in `(root)'

  2) LogStash::Filters::Date parsing with java SimpleDateFormat syntax "{"mydate":"Nov 24 01:29:01 -0800"}" when processed
     Failure/Error: insist { subject["@timestamp"].time } == Time.iso8601(output).utc
     Insist::Failure:
       Expected 2015-11-24 09:29:01 UTC, but got 2015-11-04 09:59:47 UTC
     # ./spec/filters/date_spec.rb:96:in `(root)'

  3) LogStash::Filters::Date fill last year if december events arrive in january "Dec 31 23:59:00" when processed
     Failure/Error: insist { subject["@timestamp"].year } == 2013
       (<Time (class)>).now(no args)
           expected: 2 times with any arguments
           received: 3 times
     # ./lib/logstash/filters/date.rb:275:in `filter'
     # ./lib/logstash/filters/date.rb:241:in `filter'
     # ./lib/logstash/filters/date.rb:234:in `filter'
     # (eval):33:in `filter_func'
     # ./spec/filters/date_spec.rb:413:in `(root)'
     # ./spec/filters/date_spec.rb:413:in `(root)'

Finished in 0.853 seconds (files took 1.45 seconds to load)
52 examples, 3 failures

Failed examples:


```

**Comment by jordansissel** [comment]
Reproduced manually on a digitalocean CentOS 6.7 box w/ OpenJDK 1.7.0_91

**Comment by jordansissel** [comment]
Debugging this one: `  2) LogStash::Filters::Date parsing with java SimpleDateFormat syntax "{"mydate":"Nov 24 01:29:01 -0800"}" when processed
`

pry:
```
[11] pry(#<RSpec::ExampleGroups::LogStashFiltersDate::ParsingWithJavaSimpleDateFormatSyntax::MydateNov240129010800>)> x.filter(LogStash::Event.new("mydate" => input))
Date filter: received event {:type=>nil, :level=>:debug, :file=>"logstash/filters/date.rb", :line=>"229", :method=>"filter"}
Date filter looking for field {:type=>nil, :field=>"mydate", :level=>:debug, :file=>"logstash/filters/date.rb", :line=>"232", :method=>"filter"}
Failed parsing date from field {:field=>"mydate", :value=>"Nov 24 01:29:01 -0800", :exception=>"undefined method `get' for 11:Fixnum", :config_parsers=>"MMM dd HH:mm:ss Z", :config_locale=>"default=en_US", :level=>:warn, :file=>"logstash/filters/date.rb", :line=>"272", :method=>"filter"}
```

**Comment by jordansissel** [comment]
O_o

Java 7, JRuby 1.7.23:

```
>> a = org.joda.time.format.DateTimeFormat.forPattern("MMM dd HH:mm:ss Z")
>> a.parseDateTime("Nov 20 20:20:20 -0800").month_of_year
=> 11
```

Java 8, JRuby 1.7.23

```
>> a = org.joda.time.format.DateTimeFormat.forPattern("MMM dd HH:mm:ss Z")
>> a.parseDateTime("Nov 20 20:20:20 -0800").month_of_year
=> #<Java::OrgJodaTime::DateTime::Property:0x47d90b9e>
```

Under Java 7. DateTimeFormatter#month_of_year returns 11 (a Fixnum). Under Java 8, DateTimeFormatter#month_of_year returns a DateTime::Property.

This `month_of_year` thing is JRuby squeaking around with the method table to map "java-ish" accessors to "ruby-ish" accesors. In truth, `Obj#foo_bar_baz` in JRuby/Ruby will map to a Java call of `Obj#getFooBarBaz()`.

So what's neat is that under Java 8, these return different objects:

```
>> a.parseDateTime("Nov 20 20:20:20 -0800").month_of_year
=> #<Java::OrgJodaTime::DateTime::Property:0x47d90b9e>
>> a.parseDateTime("Nov 20 20:20:20 -0800").getMonthOfYear
=> 11
```

I feel this is a JRuby bug. We can work around it by calling `getMonthOfYear` directly.

**Comment by jordansissel** [comment]
THE PLOT THICKENS.

http://www.joda.org/joda-time/apidocs/org/joda/time/DateTime.html#monthOfYear--

There's a property method `monthOfYear` and a `getMonthOfYear`. I suspect this is just JRuby ordering the method calls differently when deciding what to invoke, maybe.

Still, bug in JRuby or not, I think we really should be explicit and call the java method directly by name, not use the ruby-ish method delegation. (foo_bar -> getFooBar)

**Comment by jordansissel** [comment]
As if by magic, all 3 failing tests are fixed by c805db7. Will send a PR.

**Comment by wiibaa** [comment]
@jordansissel is there still job to be done on this as tests are green again ?
Also can you confirm #39 was a dup of this.

**Comment by wiibaa** [comment]
@suyograo can you close please
